

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt">
<!-- Mirrored from www.adventistvolunteers.org/LongTerm/SearchResults.aspx?NewListing=1&Title=New%20Listings by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 13 Nov 2017 12:03:37 GMT -->
<!-- Added by HTTrack -->

<head>

<!-- Piwik -->



<?php
//echo"<h1>Josué Corrêa</h1>";
    $call_id;
    $call_type;
    $pos_title;
    $call_org;
    $country;
    $languages;
    $beg_date;
    $end_date;
    $avs;
    $title;
    $search;
    $search_tip;
    global $LT;
    global $ST;
    
    if(count($result_c)>0){
    foreach($result_c as $key => $value){
        $call_id    =   $value->call_id;
        $call_type  =   $value->call_type;
        $pos_title  =   $value->pos_title;
        $call_org   =   $value->org_name;
        $country    =   $value->country;
        $languages  =   $value->languages;
        $beg_date   =   $value->beg_date;
        $end_date   =   $value->end_date;
        $LT         =   $value->LT;
        $ST         =   $value->ST;
        $avs        =   $value->avs;
        $title      =   $value->title;
        $search     =   $value->search;
        $search_tip =   $value->search_tip;
    }
}
    ?>


<title>
	<?php echo $avs." - ".$title; ?>
</title>
</head>

<body>
    <!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5aaa86ac4b401e45400dc328/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->


<form name="aspnetForm" method="post" action="https://www.adventistvolunteers.org/LongTerm/SearchResults.aspx?NewListing=1&amp;Title=New+Listings" id="aspnetForm">
<div>
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__LASTFOCUS" id="__LASTFOCUS" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTE4OTM3MjgwNjkPZBYCZg9kFgQCAw9kFgQCAQ9kFggCAQ8WAh4LXyFJdGVtQ291bnQCCRYSZg9kFgJmDxUDFy9TaG9ydFRlcm0vZGVmYXVsdC5hc3B4AApTaG9ydCBUZXJtZAIBD2QWAmYPFQMWL0xvbmdUZXJtL2RlZmF1bHQuYXNweAZhY3RpdmUJTG9uZyBUZXJtZAICD2QWAmYPFQMUL0dyb3Vwcy9kZWZhdWx0LmFzcHgABkdyb3Vwc2QCAw9kFgJmDxUDFS9SZXF1ZXN0L2RlZmF1bHQuYXNweAAHUmVxdWVzdGQCBA9kFgJmDxUDFi9JbnRyYURpdi9kZWZhdWx0LmFzcHgAFkNhbGxzIEluIFlvdXIgRGl2aXNpb25kAgUPZBYCZg8VAxYvQ29udGFjdHMvZGVmYXVsdC5hc3B4AApDb250YWN0IFVzZAIGD2QWAmYPFQMZL01pc3Npb25Qb3N0L2RlZmF1bHQuYXNweAAVTWlzc2lvbiBQb3N0IE1hZ2F6aW5lZAIHD2QWAmYPFQMXL1Jlc291cmNlcy9kZWZhdWx0LmFzcHgACVJlc291cmNlc2QCCA9kFgJmDxUDFy9FbWVyZ2VuY3kvZGVmYXVsdC5hc3B4AAtFbWVyZ2VuY2llc2QCAg8VCQAOY2xhc3M9J2FjdGl2ZScAAAhMb25nVGVybQlMb25nLVRlcm0MTmV3IExpc3RpbmdzCi9Mb25nVGVybS8AZAIDDxYCHwACCBYQZg9kFgJmDxUDHC9Mb25nVGVybS9RdWFsaWZpY2F0aW9ucy5odG0ADlF1YWxpZmljYXRpb25zZAIBD2QWAmYPFQMYL0xvbmdUZXJtL0hvd1RvQXBwbHkuaHRtAAxIb3cgdG8gQXBwbHlkAgIPZBYCZg8VAysvTG9uZ1Rlcm0vU2VhcmNoUmVzdWx0cy5hc3B4PyZJc05hbWVkPUZhbHNlAApWaWV3IENhbGxzZAIDD2QWAmYPFQM4L0xvbmdUZXJtL1NlYXJjaFJlc3VsdHMuYXNweD9VcmdlbnQ9MSZUaXRsZT1VcmdlbnQgQ2FsbHMABlVyZ2VudGQCBA9kFgJmDxUDPC9Mb25nVGVybS9TZWFyY2hSZXN1bHRzLmFzcHg/TmV3TGlzdGluZz0xJlRpdGxlPU5ldyBMaXN0aW5ncwAMTmV3IExpc3RpbmdzZAIFD2QWAmYPFQMaL0xvbmdUZXJtL1NlYXJjaENhbGxzLmFzcHgABlNlYXJjaGQCBg9kFgJmDxUDGi9Mb25nVGVybS9HZXR0aW5nUmVhZHkuaHRtAA1HZXR0aW5nIFJlYWR5ZAIHD2QWAmYPFQMSL0xvbmdUZXJtL0ZBUXMuaHRtAARGQVFzZAIFDxYCHg9TdGFydGluZ05vZGVVcmwFFi9Mb25nVGVybS9kZWZhdWx0LmFzcHhkAgMPZBYCAgEPZBYKAgEPZBYCAgMPFgIfAAL/////D2QCAw8PFgIeB1Zpc2libGVnZBYCZg8QDxYCHgtfIURhdGFCb3VuZGdkZBYBZmQCBQ8WBB8AAgIfAmcWBAIBD2QWBGYPFQILTmV3IExpc3RpbmcBMWQCAQ8PFgIeC05hdmlnYXRlVXJsBTAvTG9uZ1Rlcm0vU2VhcmNoUmVzdWx0cy5hc3B4PyZUaXRsZT1OZXcgTGlzdGluZ3NkZAICD2QWBGYPFQIMU2VydmljZSBUeXBlCUxvbmcgVGVybWQCAQ8PFgIfBAU9L0xvbmdUZXJtL1NlYXJjaFJlc3VsdHMuYXNweD8mTmV3TGlzdGluZz0xJlRpdGxlPU5ldyBMaXN0aW5nc2RkAgcPZBYCAgEPEA8WAh8DZ2QQFRYUW1NlbGVjdCBGaWx0ZXIgVHlwZV0JQWdlIChNYXgpCUFnZSAoTWluKQ9DYWxsaW5nIENvdW50cnkNQ2FsbGluZyBEL1UvQxFDYWxsaW5nIE9yZyBBYnJldh1DaGlsZCBBY2NvbW1vZGF0aW9uIEF2YWlsYWJsZQZHZW5kZXIbSGFzIEF2YWlsYWJsZSAobm9uLXBlbmRpbmcpCExhbmd1YWdlFExlbmd0aCBHcmVhdGVyL0VxdWFsEUxlbmd0aCBMZXNzL0VxdWFsDk1hcml0YWwgU3RhdHVzDk1heCBFZHVjIExldmVsDk1pbiBFZHVjIExldmVsCk5hbWVkIENhbGwPTmFtZWQgVm9sdW50ZWVyGE9ubHkgU2hvdyBJbnRyYS1EaXZpc2lvbg5Qb3NpdGlvbiBUaXRsZQ1Qb3NpdGlvbiBUeXBlElZvbCBGcm9tIE9yZyBMZXZlbAxZZWFyIG9mIENhbGwVFgAGQWdlTWF4BkFnZU1pbg1DYWxsaW5nQ3RyeUlECUNhbGxpbmdBRghPcmdBYnJldg9DaGlsZEFjY29tQXZhaWwGR2VuZGVyFkhhc0F2YWlsYWJsZU5vblBlbmRpbmcGTGFuZ0lECUxlbmd0aEdURQlMZW5ndGhMVEUNTWFyaXRhbFN0YXR1cw5NYXhFZHVjTGV2ZWxJRA5NaW5FZHVjTGV2ZWxJRAdJc05hbWVkCE5hbWVkVm9sCUludHJhT25seQdTUlRpdGxlDlBvc2l0aW9uVHlwZUlED1ZvbEZyb21PcmdMZXZlbAhDYWxsWWVhchQrAxZnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnFgFmZAIJD2QWAmYPZBYEAgEPPCsAEQMADxYEHwNnHwACHmQBEBYAFgAWAAwUKwAAFgJmD2QWQGYPDxYCHgxUYWJsZVNlY3Rpb24LKilTeXN0ZW0uV2ViLlVJLldlYkNvbnRyb2xzLlRhYmxlUm93U2VjdGlvbgBkZAIBD2QWDGYPZBYCZg8VARFOQUQuUEFBVEEuMjAxNy4wMWQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODE0OGQWAmYPFQESRWxlbWVudGFyeSBUZWFjaGVyZAICDxUBGlBhYXRhIElzbGFuZCBTY2hvb2wsIENodXVrZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEmTWljcm9uZXNpYSwgRlMgb2YvQ2h1dWsgLyBQQUFUQSBJU0xBTkRkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB4LRm9udF9JdGFsaWNoHgRfIVNCAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxNy0wNS0wMQoyMDE4LTA2LTAyZAICD2QWDGYPZBYCZg8VAQ9FVUQuSVVDLjIwMTguMDFkAgEPZBYEAgEPDxYCHwQFHFZpZXdDYWxsLmFzcHg/U3ZjUmVxSUQ9MTg1MDFkFgJmDxUBEFZpZGVvIFByb2R1Y3Rpb25kAgIPFQEkSXRhbGlhbiBVbmlvbiBvZiBDaHVyY2hlcyBDb25mZXJlbmNlZAICD2QWBGYPFQIDMDAyATJkAgEPDxYCHwJoZBYCZg8VAQEyZAIDD2QWAmYPFQEFSXRhbHlkAgQPZBYCAgEPFgIfAAIDFgZmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAICD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdJdGFsaWFuZAIED2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdTcGFuaXNoZAIFD2QWAmYPFQIKMjAxOC0wMS0wMQoyMDE5LTEyLTMxZAIDD2QWDGYPZBYCZg8VARFTQUQuRkFEQkEuMjAxOC4wMWQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODU0NGQWAmYPFQEPRW5nbGlzaCBUZWFjaGVyZAICDxUBGE5vcnRoZWFzdCBCcmF6aWwgQ29sbGVnZWQCAg9kFgRmDxUCAzAwMgEyZAIBDw8WAh8CaGQWAmYPFQEBMmQCAw9kFgJmDxUBBkJyYXppbGQCBA9kFgICAQ8WAh8AAgIWBGYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgIPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBClBvcnR1Z3Vlc2VkAgUPZBYCZg8VAgoyMDE4LTAxLTE1CjIwMTgtMTItMTVkAgQPZBYMZg9kFgJmDxUBD0lBRC5VTk0uMjAxOC4wMWQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODU3MmQWAmYPFQEQIEVuZ2xpc2ggVGVhY2hlcmQCAg8VARdNb250ZW1vcmVsb3MgVW5pdmVyc2l0eWQCAg9kFgRmDxUCAzAwMQExZAIBDw8WAh8CaGQWAmYPFQEBMWQCAw9kFgJmDxUBBk1leGljb2QCBA9kFgICAQ8WAh8AAgIWBGYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgIPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBBkdlcm1hbmQCBQ9kFgJmDxUCCjIwMTgtMDEtMTUKMjAxOC0xMi0xNWQCBQ9kFgxmD2QWAmYPFQEPSUFELlVOTS4yMDE4LjAyZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NTc1ZBYCZg8VARZNdWx0aS1MYW5ndWFnZSBUZWFjaGVyZAICDxUBF01vbnRlbW9yZWxvcyBVbml2ZXJzaXR5ZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEGTWV4aWNvZAIED2QWAgIBDxYCHwACAxYGZg9kFgICAQ8PFgQfBmgfBwKAIGQWAmYPFQEHRW5nbGlzaGQCAg9kFgICAQ8PFgQfBmgfBwKAIGQWAmYPFQEGR2VybWFuZAIED2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQZGcmVuY2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEwCjIwMTktMDgtMTVkAgYPZBYMZg9kFgJmDxUBD1NBRC5BQ1AuMjAxOC4wMWQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODU5MWQWAmYPFQEzQ29tcHV0ZXIgQXJ0IERlc2lnbmVyLCBWaWRlbyBFZGl0b3IgYW5kIEVTTCBUZWFjaGVyZAICDxUBGUNlbnRyYWwgUGFyYW5hIENvbmZlcmVuY2VkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VAQZCcmF6aWxkAgQPZBYCAgEPFgIfAAICFgRmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAICD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdTcGFuaXNoZAIFD2QWAmYPFQIKMjAxOC0wMS0xNQoyMDE4LTEyLTE1ZAIHD2QWDGYPZBYCZg8VAQ5OQUQuQ0suMjAxOC4wOGQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYwMWQWAmYPFQEfN3RoLTEydGggR3JhZGVzIEhpc3RvcnkgVGVhY2hlcmQCAg8VARBDaHV1ayBTREEgU2Nob29sZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEXTWljcm9uZXNpYSwgRlMgb2YvQ2h1dWtkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxOC0wOC0xMgoyMDE5LTA2LTAzZAIID2QWDGYPZBYCZg8VAQ5OQUQuQ0suMjAxOC4wOWQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYxMmQWAmYPFQEfN3RoLTEydGggR3JhZGVzIEVuZ2xpc2ggVGVhY2hlcmQCAg8VARBDaHV1ayBTREEgU2Nob29sZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEXTWljcm9uZXNpYSwgRlMgb2YvQ2h1dWtkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxOC0wOC0xMgoyMDE5LTA2LTAzZAIJD2QWDGYPZBYCZg8VAQ5OQUQuS0MuMjAxOC4wMWQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYxOGQWAmYPFQErQ2hhcGxhaW4vTGlhaXNvbiBmb3IgSW50ZXJuYXRpb25hbCBTdHVkZW50c2QCAg8VARBLaW5nc3dheSBDb2xsZWdlZAICD2QWBGYPFQIDMDAyATJkAgEPDxYCHwJoZBYCZg8VAQEyZAIDD2QWAmYPFQEGQ2FuYWRhZAIED2QWAgIBDxYCHwACAhYEZg9kFgICAQ8PFgQfBmgfBwKAIGQWAmYPFQEUQnJhemlsaWFuIFBvcnR1Z2VzZSBkAgIPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTAyLTAxCjIwMTktMDItMjJkAgoPZBYMZg9kFgJmDxUBDk5BRC5DSy4yMDE4LjEwZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjE5ZBYCZg8VARw3dGgtMTJ0aCBHcmFkZXMgTWF0aCBUZWFjaGVyZAICDxUBEENodXVrIFNEQSBTY2hvb2xkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VARdNaWNyb25lc2lhLCBGUyBvZi9DaHV1a2QCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAgsPZBYMZg9kFgJmDxUBDk5BRC5DSy4yMDE4LjExZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjIwZBYCZg8VAShDaGFwbGFpbiAmIDd0aC0xMnRoIEdyYWRlcyBCaWJsZSBUZWFjaGVyZAICDxUBEENodXVrIFNEQSBTY2hvb2xkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VARdNaWNyb25lc2lhLCBGUyBvZi9DaHV1a2QCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAgwPZBYMZg9kFgJmDxUBDk5BRC5DSy4yMDE4LjEyZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjIxZBYCZg8VASA3dGgtMTJ0aCBHcmFkZXMgQ29tcHV0ZXIgVGVhY2hlcmQCAg8VARBDaHV1ayBTREEgU2Nob29sZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEXTWljcm9uZXNpYSwgRlMgb2YvQ2h1dWtkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxOC0wOC0xMgoyMDE5LTA2LTAzZAIND2QWDGYPZBYCZg8VAQ5OQUQuQ0suMjAxOC4xM2QCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYyMmQWAmYPFQEfN3RoLTEydGggR3JhZGVzIFNjaWVuY2UgVGVhY2hlcmQCAg8VARBDaHV1ayBTREEgU2Nob29sZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEXTWljcm9uZXNpYSwgRlMgb2YvQ2h1dWtkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxOC0wOC0xMgoyMDE5LTA2LTAzZAIOD2QWDGYPZBYCZg8VARFOQUQuUEFBVEEuMjAxOC4wMWQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYyM2QWAmYPFQEgS2luZGVyZ2FydGVuIC0gMm5kIEdyYWRlIFRlYWNoZXJkAgIPFQEaUGFhdGEgSXNsYW5kIFNjaG9vbCwgQ2h1dWtkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VASZNaWNyb25lc2lhLCBGUyBvZi9DaHV1ayAvIFBBQVRBIElTTEFORGQCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAg8PZBYMZg9kFgJmDxUBEU5BRC5QQUFUQS4yMDE4LjAyZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjI0ZBYCZg8VARgzcmQgJiA0dGggR3JhZGVzIFRlYWNoZXJkAgIPFQEaUGFhdGEgSXNsYW5kIFNjaG9vbCwgQ2h1dWtkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VASZNaWNyb25lc2lhLCBGUyBvZi9DaHV1ayAvIFBBQVRBIElTTEFORGQCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAhAPZBYMZg9kFgJmDxUBEU5BRC5QQUFUQS4yMDE4LjAzZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjI1ZBYCZg8VARg1dGggJiA2dGggR3JhZGVzIFRlYWNoZXJkAgIPFQEaUGFhdGEgSXNsYW5kIFNjaG9vbCwgQ2h1dWtkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VASZNaWNyb25lc2lhLCBGUyBvZi9DaHV1ayAvIFBBQVRBIElTTEFORGQCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAhEPZBYMZg9kFgJmDxUBDk5BRC5DSy4yMDE4LjE0ZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjI2ZBYCZg8VARJNYWludGVuYW5jZSBXb3JrZXJkAgIPFQEQQ2h1dWsgU0RBIFNjaG9vbGQCAg9kFgRmDxUCAzAwMQExZAIBDw8WAh8CaGQWAmYPFQEBMWQCAw9kFgJmDxUBF01pY3JvbmVzaWEsIEZTIG9mL0NodXVrZAIED2QWAgIBDxYCHwACARYCZg9kFgICAQ8PFgQfBmgfBwKAIGQWAmYPFQEHRW5nbGlzaGQCBQ9kFgJmDxUCCjIwMTgtMDgtMTIKMjAxOS0wNi0wM2QCEg9kFgxmD2QWAmYPFQEOTkFELkNLLjIwMTguMTVkAgEPZBYEAgEPDxYCHwQFHFZpZXdDYWxsLmFzcHg/U3ZjUmVxSUQ9MTg2MjdkFgJmDxUBCkFjY291bnRhbnRkAgIPFQEQQ2h1dWsgU0RBIFNjaG9vbGQCAg9kFgRmDxUCAzAwMQExZAIBDw8WAh8CaGQWAmYPFQEBMWQCAw9kFgJmDxUBF01pY3JvbmVzaWEsIEZTIG9mL0NodXVrZAIED2QWAgIBDxYCHwACARYCZg9kFgICAQ8PFgQfBmgfBwKAIGQWAmYPFQEHRW5nbGlzaGQCBQ9kFgJmDxUCCjIwMTgtMDgtMTIKMjAxOS0wNi0wM2QCEw9kFgxmD2QWAmYPFQEPTkFELllBUC4yMDE4LjAxZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjI4ZBYCZg8VARExc3QgR3JhZGUgVGVhY2hlcmQCAg8VAQ5ZYXAgU0RBIFNjaG9vbGQCAg9kFgRmDxUCAzAwMQExZAIBDw8WAh8CaGQWAmYPFQEBMWQCAw9kFgJmDxUBFU1pY3JvbmVzaWEsIEZTIG9mL1lhcGQCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAhQPZBYMZg9kFgJmDxUBD05BRC5ZQVAuMjAxOC4wMmQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYyOWQWAmYPFQERM3JkIEdyYWRlIFRlYWNoZXJkAgIPFQEOWWFwIFNEQSBTY2hvb2xkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VARVNaWNyb25lc2lhLCBGUyBvZi9ZYXBkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxOC0wOC0xMgoyMDE5LTA2LTAzZAIVD2QWDGYPZBYCZg8VAQ9OQUQuWUFQLjIwMTguMDNkAgEPZBYEAgEPDxYCHwQFHFZpZXdDYWxsLmFzcHg/U3ZjUmVxSUQ9MTg2MzNkFgJmDxUBETV0aCBHcmFkZSBUZWFjaGVyZAICDxUBDllhcCBTREEgU2Nob29sZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEVTWljcm9uZXNpYSwgRlMgb2YvWWFwZAIED2QWAgIBDxYCHwACARYCZg9kFgICAQ8PFgQfBmgfBwKAIGQWAmYPFQEHRW5nbGlzaGQCBQ9kFgJmDxUCCjIwMTgtMDgtMTIKMjAxOS0wNi0wM2QCFg9kFgxmD2QWAmYPFQEPTkFELllBUC4yMDE4LjA0ZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjM0ZBYCZg8VARE2dGggR3JhZGUgVGVhY2hlcmQCAg8VAQ5ZYXAgU0RBIFNjaG9vbGQCAg9kFgRmDxUCAzAwMQExZAIBDw8WAh8CaGQWAmYPFQEBMWQCAw9kFgJmDxUBFU1pY3JvbmVzaWEsIEZTIG9mL1lhcGQCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAhcPZBYMZg9kFgJmDxUBD05BRC5ZQVAuMjAxOC4wNWQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYzNWQWAmYPFQEfN3RoLTEydGggR3JhZGVzIFNjaWVuY2UgVGVhY2hlcmQCAg8VAQ5ZYXAgU0RBIFNjaG9vbGQCAg9kFgRmDxUCAzAwMQExZAIBDw8WAh8CaGQWAmYPFQEBMWQCAw9kFgJmDxUBFU1pY3JvbmVzaWEsIEZTIG9mL1lhcGQCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAhgPZBYMZg9kFgJmDxUBD05BRC5ZQVAuMjAxOC4wNmQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYzNmQWAmYPFQEcN3RoLTEydGggR3JhZGVzIE1hdGggVGVhY2hlcmQCAg8VAQ5ZYXAgU0RBIFNjaG9vbGQCAg9kFgRmDxUCAzAwMQExZAIBDw8WAh8CaGQWAmYPFQEBMWQCAw9kFgJmDxUBFU1pY3JvbmVzaWEsIEZTIG9mL1lhcGQCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAhkPZBYMZg9kFgJmDxUBD05BRC5ZQVAuMjAxOC4wN2QCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYzN2QWAmYPFQEfN3RoLTEydGggR3JhZGVzIEVuZ2xpc2ggVGVhY2hlcmQCAg8VAQ5ZYXAgU0RBIFNjaG9vbGQCAg9kFgRmDxUCAzAwMQExZAIBDw8WAh8CaGQWAmYPFQEBMWQCAw9kFgJmDxUBFU1pY3JvbmVzaWEsIEZTIG9mL1lhcGQCBA9kFgICAQ8WAh8AAgEWAmYPZBYCAgEPDxYEHwZoHwcCgCBkFgJmDxUBB0VuZ2xpc2hkAgUPZBYCZg8VAgoyMDE4LTA4LTEyCjIwMTktMDYtMDNkAhoPZBYMZg9kFgJmDxUBD05BRC5ZQVAuMjAxOC4wOGQCAQ9kFgQCAQ8PFgIfBAUcVmlld0NhbGwuYXNweD9TdmNSZXFJRD0xODYzOGQWAmYPFQEdN3RoLTEydGggR3JhZGVzIEJpYmxlIFRlYWNoZXJkAgIPFQEOWWFwIFNEQSBTY2hvb2xkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VARVNaWNyb25lc2lhLCBGUyBvZi9ZYXBkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxOC0wOC0xMgoyMDE5LTA2LTAzZAIbD2QWDGYPZBYCZg8VAQ9OQUQuWUFQLjIwMTguMDlkAgEPZBYEAgEPDxYCHwQFHFZpZXdDYWxsLmFzcHg/U3ZjUmVxSUQ9MTg2MzlkFgJmDxUBIDd0aC0xMnRoIEdyYWRlcyBDb21wdXRlciBUZWFjaGVyZAICDxUBDllhcCBTREEgU2Nob29sZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEVTWljcm9uZXNpYSwgRlMgb2YvWWFwZAIED2QWAgIBDxYCHwACARYCZg9kFgICAQ8PFgQfBmgfBwKAIGQWAmYPFQEHRW5nbGlzaGQCBQ9kFgJmDxUCCjIwMTgtMDgtMTIKMjAxOS0wNi0wM2QCHA9kFgxmD2QWAmYPFQEPTkFELllBUC4yMDE4LjEwZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjQwZBYCZg8VASo3dGgtMTJ0aCBHcmFkZXMgUGh5c2ljYWwgRWR1Y2F0aW9uIFRlYWNoZXJkAgIPFQEOWWFwIFNEQSBTY2hvb2xkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VARVNaWNyb25lc2lhLCBGUyBvZi9ZYXBkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxOC0wOC0xMgoyMDE5LTA2LTAzZAIdD2QWDGYPZBYCZg8VAQ9OQUQuWUFQLjIwMTguMTFkAgEPZBYEAgEPDxYCHwQFHFZpZXdDYWxsLmFzcHg/U3ZjUmVxSUQ9MTg2NDFkFgJmDxUBJjd0aC0xMnRoIEdyYWRlcyBTb2NpYWwgU3R1ZGllcyBUZWFjaGVyZAICDxUBDllhcCBTREEgU2Nob29sZAICD2QWBGYPFQIDMDAxATFkAgEPDxYCHwJoZBYCZg8VAQExZAIDD2QWAmYPFQEVTWljcm9uZXNpYSwgRlMgb2YvWWFwZAIED2QWAgIBDxYCHwACARYCZg9kFgICAQ8PFgQfBmgfBwKAIGQWAmYPFQEHRW5nbGlzaGQCBQ9kFgJmDxUCCjIwMTgtMDgtMTIKMjAxOS0wNi0wM2QCHg9kFgxmD2QWAmYPFQEPTkFELllBUC4yMDE4LjEyZAIBD2QWBAIBDw8WAh8EBRxWaWV3Q2FsbC5hc3B4P1N2Y1JlcUlEPTE4NjQyZBYCZg8VARJNYWludGVuYW5jZSBXb3JrZXJkAgIPFQEOWWFwIFNEQSBTY2hvb2xkAgIPZBYEZg8VAgMwMDEBMWQCAQ8PFgIfAmhkFgJmDxUBATFkAgMPZBYCZg8VARVNaWNyb25lc2lhLCBGUyBvZi9ZYXBkAgQPZBYCAgEPFgIfAAIBFgJmD2QWAgIBDw8WBB8GaB8HAoAgZBYCZg8VAQdFbmdsaXNoZAIFD2QWAmYPFQIKMjAxOC0wOC0xMgoyMDE5LTA2LTAzZAIfDw8WBB8FCysEAh8CaGRkAgIPFQEpY3RsMDBfY3BoQm9keV9TZWFyY2hSZXN1bHRzMV9jdGwwMV9ndkxpc3RkAgUPZBYCAgMPFgIfAAIJFhJmD2QWAmYPFQMXL1Nob3J0VGVybS9kZWZhdWx0LmFzcHgAClNob3J0IFRlcm1kAgEPZBYCZg8VAxYvTG9uZ1Rlcm0vZGVmYXVsdC5hc3B4BmFjdGl2ZQlMb25nIFRlcm1kAgIPZBYCZg8VAxQvR3JvdXBzL2RlZmF1bHQuYXNweAAGR3JvdXBzZAIDD2QWAmYPFQMVL1JlcXVlc3QvZGVmYXVsdC5hc3B4AAdSZXF1ZXN0ZAIED2QWAmYPFQMWL0ludHJhRGl2L2RlZmF1bHQuYXNweAAWQ2FsbHMgSW4gWW91ciBEaXZpc2lvbmQCBQ9kFgJmDxUDFi9Db250YWN0cy9kZWZhdWx0LmFzcHgACkNvbnRhY3QgVXNkAgYPZBYCZg8VAxkvTWlzc2lvblBvc3QvZGVmYXVsdC5hc3B4ABVNaXNzaW9uIFBvc3QgTWFnYXppbmVkAgcPZBYCZg8VAxcvUmVzb3VyY2VzL2RlZmF1bHQuYXNweAAJUmVzb3VyY2VzZAIID2QWAmYPFQMXL0VtZXJnZW5jeS9kZWZhdWx0LmFzcHgAC0VtZXJnZW5jaWVzZBgBBSljdGwwMCRjcGhCb2R5JFNlYXJjaFJlc3VsdHMxJGN0bDAxJGd2TGlzdA88KwAMAQgCAWSlWWRfOkVfb1z5a26J31hm2VnDGYC7pmOEl0HqVw7xAw==" />
</div>


<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="21DDE81A" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdAI0CfD6YvVOkUeerpapQfzYJwAqY8C0GLi1S8npsfm66BnRDYRn2emlf+jIeuKtS4fCXf/I3+uFv6qywGQ0/YuqDU4bLoGLjvP/PzXMwU+6syg9NLAx9D8KYzAn0lQLRKJO8dZ5DUFOyrRfZJeR+ia1bUq9H0b/RFGgtzKFN3c5rRRgkRJ6C8tFM6SDfvoqebMOKYPHUv7IU2/+h3nvZvtQhxbkCnMq0HH7tK09dTLkgUh9tbUA4dsB4U6RG5dfmerdf4ohY9Ji27G1Y0jxzuu3TJxtjPTSA1Ql4WgWmTBFl1H9f8Z7u3MSu6EZLzMAQEwYFieyMgLwUNaUczTge0Zv6Gin4OuTs9O6bP+omJrGJ4xYGBf0j5NBaZy4tCRhSgYM4hKzoF2aPM0ygOOtjNRiI1VgmLtqo6aAXifDBy7Z2R2gTT8w6+7uz56CwGHZ3oD/C4HdgWSVi5W3bbftQBVwWoSf4x0ByM1ePQgOCpnDTlMMEGEjzJnuX7CmA/Wwv4vXz1xbPm4m1y8tbEfKhVMzAMGGtV0NMMDocLmT3ZB/dEqttY0qCl8SHj8MUbo0t4CRzlrMNpkFIyaQuDlrhLhg39vk3KzfDao/vSCX+IiudccA0njH8lJbEAGTMuh4gPzDIoGr8KqvYEBpTaM7nyXUNXEuFy7htjmbaOe8ZZsN//zeh2lxqCTuMEt6WvFmaL7IUgJyWu3Dr7tyTWweIL3izzUJ8lEYumIi4TAqjp9ZOVwTIB/E4+TkfRV9iQk17bfISRoOKi/FPaR0lvUWC9Jy2SVaWLL1+ZrcrDHvy1HEfMKPY84j+jtwuNxulkFstaWBmAfhB8yRiaiRXNXNyrUdmxKysK4LDKL9t/2cuxxsjfmHXrDYrCIQXVED+NP3lwPXw576v1Yf/8hUAHdhuMwBms47oOgy5OJTyon3w1mzmVpAIQAegRDdRgFDoDXurnvEHoRBjBvFEYxbAhPIaHBcjYs78GdzRWQ4Xdc62NxJjddujV2vCGyjIzTth6xbc4g5LPmdVmbfjXunjwA1UMWPD3W12QQZBbO3M6oVzyS9n+1Mn5PVRr/6xkaStubOEn84zzQG75nq9w75NDszts7YO5zAvb1pewSoz6Nq0scpgaVeuUDGUZYMWRaOqREquKu/mVgSckMo1RQv3DSrjQBucgC6xOqVDneObBLyfyFnO1fIo2PWw3o5Y11t21V1RCJ5xsZwBrX7xIXcXdDi1+hnih+H/Ggtn/3s4HPLS7v30lXST3bfQvURh5dOz1r5IPtub+IFfQq46gwBegqtPG7ZziTJrU5DAdVQj4H9q83MVi2lLJyd2KhMEx6RpcFP/ZjajZ3eNONq926lPYev3ChfuPvhLQRHGjBNx3KxcxCJWWxh+dhFt9Gzh37rTNxSbJVQZ5nGnuWL9N11Ea13MyqcZYc37p9zwejytJ4t0sHkKRd8S5omAjor21Vhxe7r7eV1E7WWdAfji2jOvnKoVz3wL57h8fUcjLobJJIUDJ0AiSFHw16F6Zo5ZGbOdPSQN3bv+rJ5dDB7Y4tMeCj6KuZVLV8Ww8vhmNTx+A1ksvN4pEM96au+zE+4G0MBjICuv7biRPwiKP58KI8vCTKaxZ0tA7pIwReRUuiR7aBzS4GBNscl33ugLYouKA49nd6SM/g3pFDpgoDXQ0GwbQekJN/ukKg9T8S8b0yQcXiyHIqZny3uJqEp8WO09nekpXHdixTYkr2aBI+DhxtGiPL12tBQRuzA+oATIPd022OIW6qoNy6FOulOaX4h6MUgqUNAsW68dBCsiuPR5bUO878qLTGf3mqCzTgEd0V6jhDQnHSPgaktc49VHNbOWeZTdfIn13XIdBxy45zQmrU7S/MBZlo9OWvkLpzFu13Z1OZ7tv+v29ewh5QQD3D+b8GtGSBePwGdH2ZTUFUsLDL7x1kQYrFJUAv9YuZOECJ0z/YAMmBNvewbTYPP4YSC27swvpcoAxf9ZQdMGBf0qJ7EVN6Uv+WEjqZY32/53iEDCi0mHe9PZApTWHAjWjF1SwQm0PDFNZbS4jfRdRbzeTI9M2bi0zIImeAG/ow9DFLAKLNA1nZ30jevw+dv+ZLo36Q5U58J35Xoi6qmfap4POuJIzG+fbsMvL6bjwKjby0fvMIDDHzy4M4ZoQpsqXGjN1LCfWx/VQol29PZ4A8zLAISmdGTxlDNTKVeCnyDMZiiz+WqUm0I23dXID62SVBjEkOTpyLLEmr9KuofXGvgYlCWrx5wtxYrQR63KJu0DtYDu/+kQy0xNLlmpy3UCF8nIdBbL/60R361YNtJ1YEdq7Cmzb2UBvjFiXwjGkCDDag5z5634nHK/JYutKfiPZX0GzHlmJx9N+8PRzKsZVdiED2spdrubEXmT2nvjgUYAkO7zIJzENso2RYtJd2BdA6eyjbdFgsEr2+BP0m90r85JhgALJvu8hXmOvfZZFnqcJt+A7bXCRIMRXHGX7hWTrJiqPhYcthKMAmxrsWakLi921vHqiFsEVe/2dIAWCw87rnFVQCsXw6Gk0xdL63qNJ3yK6RZLXRRDWU9GPp2t9yRxpdNTx4hYuDVhnZdTo1J8xzmcO6pXStSFAjfpu1Cz3C1s6l2oyM1Fbt8C6ren2X8B0ruwUMR2+yE9M7uR/y1xdAawll9zDLb/K4Ufp8nJjWaQqYH+pFWWpT+Z/7IJOfSf8yPBAHy/mAUsJjfCKVRPX3CeJZYsKsdNeVon8Z8UEpyXvUhuqGy+7rZykY4nHb+xEhXZ7AdNFd1J66Nth9mww3BRon1Rp1HNllWSOdWGX5dpZurEqKHp13rwHjVXZr7d+K3sf27ruNGQAmDOGzTphbaA9Hkx+SeoCKtrlVemZGU+10cyQyB4wpT4TNsGOIy0vJQeZemza3Myy4bPbpsLyofYHIsF0A1w2Uzifn9zmaj8BW9AMcLWbh8qZ8u12Hcvrb/fDF4YVdhLiuQAxWgTbz+hua3lmH+pXMTtk8mUcZVw97Ls3xoKavmK/RuRF7X0aC4YTpKad1PRSQbRC3vep3n+EDLHvu05jTg6/NRSeuXD9RMkl/aipRmh+V4/4/Oy3wHS/AHGGCzU3ZM2M3FgC1EVSupllstVe7HTX8nk1QYjDGOSn+rA1PKRR1lCErMRO1O8WrC53BZZYywaYymMsJ89qloauwL8ZDrDUy6FW+sgnwLaf4CEDrxxjsqsL9haJBgaVlhgRSyg7kVNhM1i+o65QUWlZAoFYQNzLTZnjL6zMLv+Bp9tZvlGLXvG2bkFI/cHw4nFIDPlZcAuRgmwD6lWlj01RODDlRN4Rbx9Xng2IlKN7QRHsxXA7MhDTDAyGM5WSvWP3OxzHqJcxy7cjTZPVaxr2efqyHVsDa2c6DdagjxHyD6g0t+I9QaUCZBwc5Bpbr250WCzxjKGu2V9i4rYpDkx4XfyxzQYHwLwId8IjLcGAk5JpH/PYxDMcRM+VZ4fzpncDacutJmGl3jsNH9iSRFl6VXQnfEnK+AOD8SfKunug23sJwsDhw06sKzdl9awPxOodJ+KOQaWnsV10Beub/MOTRZ6SvoPHsi/vf7glTPKVnueQwd+IuKBt1vgDUTSshGmsLtqeJyLcmtHsNvm1RJYrT9hMzPi6+dX/c9KnMcC8G29vng8jNDWDWsCgVdol3OBdY1/hhYAsEMBDfxZIQ4dMFt/ujiS8WuniylnNJ5at+gscml2sJFDpfuAhK+aB+uHfg19w4KDgZ7xwPcrS04SpvnOQqspBpg537tOBlQmCx5XhAuXvXVp8WbE2jQfmQNrx+KxvmGg0QEimbXQaMvQyrD2NuvwSOq1bmPD3bjb3uALVwwMP/3B0JGUbG7YGM7oTmFfoR9lr0SZBvXpDkcIel1EKS9Dg/rGhYim7BCSW5n/ShnVTmFRtuzNb1DIUdibNgH7ZexRBbR5RoIUe9vKrjnigLoMYxJHsnfQlkGJ5pGyWdS4BssK3T1BJUjLvXyUnBYA5gqZo5egV2cXd2/SWIxQzoyhfDqZTU2+kH8aeEJ36VVD5LZJHagUMUXZcc8QWps+aozOLIUBIJByKRtlBJNdcwLsMrj4UD9tlqtSOUdiLYxuZztChS0GCaEvt1fcxueFIUANXWeeOuIJRVKyxu8yETysBDHTpa3TgM8oYEwFBOBHFcHXuFVAk2N0XmzjP/Ndr/SBcz1i+r/sqqFnJls9cixL62NAVQ4dGQpYU3QZte9av5KMb8MBLf2E4Zt4BNPY9sLZEX7VcqaGjOqbYh80ZhgD6x8LB+oNeK3C2N6V3tTuzDWFipzgM/BzxMwkLdswBLeCwNGmWSSjv8ZrbMZIIKL/Lh2PFt0yvwB3hXZ2iSAo9Wh+H5vq31IfvYpt7aNMaB5d9hbM3azxrMNKAReIwFGQWZZsrpNbMFR4Y0FjvR7lamr63K1/0YTQby5O3fdKuvhckjB5wQaTGk70zxBGru2aAdMk3gGiZQ4lW+mbZ2LvNrj8IucItmh0XOXKP+WaTh48O7lkv1Fh4UBxpApB0Zg5r5VhMlN/sXCTYfFgY7aXbFjMkKythvTEz/cPb6SrynOqwgg09tRPj6njGvNO9zHk/01M2pby8oxDTPbm/w2TV4dUkEJm7XtI/hU4xSH5+r06zaWefgFRsWyzdaT9TTfHveV7n59NVej3HLhICY9rSwc3zxXUlH0eyt6/hpMAr8kc7hDIlKT0csD07dr409k8eckiMJ9TJDEQuLw8NiJcci5mebv3WG8iNhzJ1dMVuVblwFGnqklCkorKPMzHU8RJAwdHIZyVWWADR9KmzatkjIOsXQS6fvy12BCN6MCHif3m97wMeTin/9EU2A1snnYPOaflL1uPOSKtiJccPg8gdWJufORqFfgCHt8TyAYrANnMkvRHkzV22B1GjNF6U/LKMjz6G1Ngt0+fsMLXfQinfSZ9tlILPZBwSBdSKc0KN04FxZ/hmek70VeSlYHc/rsnm3TpUlLjuLUB0/SnEc9XERYxPy5+5KoQKcOG9+++iOUQy8U+W4gEVRyj0EGtlB+C2IfdZonczrDp/4at8w9McHw28BLHm7U5SErnEcW0UBZg9D43HqhZBc47G4aWy5vl4KFkB/qaoNMUPSQH4Rhus5dm9WGs92p+lNDFGmaSpmDvmbNx89ZNgJcXZOmcXb64PD226++bT32qZxPBcEgzK5juUkiiSeS9hlEuNLTT8P6YMvIE35pbNLnTVC528fY3sFfgI9Ggw2KDA2VR5npH354JUQEM0KzCmYNed+AQiWY/uKOZw7Yqfge67p7/4J10kDqG6r8+XyrI7IuibUP+TJFSlDV+2mULAyBD7hrrEkH5vhcvzU/+mWTKNuHL6kwb0/7D7MvyG59PTl3MXIiiVxj3EtID8KoD6Q1ZC13dX4CfKkMkWuOIpn5YtokU/InyKoRwjKqX617osbdkAtOMHCaYYSPOVuQx/XCqGeyPsYcMRnBHr2u4Q1GxdVsjIc2GaFn5Pq+cWb1tZCK4tl/eetNNtIeD7r4ZqLoNfDyIeieijnKZZARZ2GTKZZNQoK+ApWVMi8jrwKaxlWfYM2Pcn58O96Do4KhF2sguDTiGKQHHvCSZOOB1pb0M5PjR1nwRYqn8Um0G+lbmTDit2+NrUesIjAUCrS6oyrjiaCDXkwEp5LEj9UCBmfmkq82krXtohdW7UqgZ36vJCq/G9MBU8s15kKaklZwwk0sRinvdOP3eXgS52qU6ScU2SX2W/hEbiCHmwPXOwDzTwl90N+L60iDU5wKGmh0/PMpVwyjYGA==" />
</div>
<div id="container-outer">
<div id="ctl00_pnlHeader">
    <div id="head-sub">
    	<div id="topNav" class="centerNav">
        	




</ul>
        </div>
        <div class="clear"></div>      
        <div id="subNav" class="centerNav">
        	



</div>     
  </div>

</div>  
    <div id="content">



<div id="ctl00_cphBody_SearchResults1_pnlOnlyGlobal">
	




<div>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 0px solid #e8eff9;
            text-align: left;
            padding: 0px;
        }

        tr:nth-child(even) {
            background-color: #e8eff9;
        }
        @media print { 
            #content table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }

            #content td, th {
                border: 0px solid #e8eff9;
                text-align: left;
                padding: 0px;
            }

            #content tr:nth-child(even) {
                background-color: #e8eff9;
            }
           }  
    </style>
	<table class="display" cellspacing="0" rules="all" border="0" id="ctl00_cphBody_SearchResults1_ctl01_gvList" style="border-collapse:collapse;">
		<thead>
                    
                    
			<tr class="listheader" valign="bottom">
                            <?php
                                echo 
                                    "<th scope=\"col\">".$call_id."</th>
                                    <th scope=\"col\">".$call_type."</th>
                                    <th scope=\"col\">".$pos_title."<br>".$call_org."</th>
                                    <th scope=\"col\">".$country."</th>
                                    <th scope=\"col\">".$languages."</th>
                                    <th scope=\"col\">".$beg_date."<br>".$end_date."</th>";
                            ?>
                        </tr>
		</thead>
            <tbody>
                <?php
                function term($num){
                    global $LT;
                    global $ST;
                    if($num === "LTG" or $num === "LTI"){
                        return $LT." ";
                    }
                    else{
                        return $ST." ";
                    }
                }
             
                $pattern = "[\((.*?),|\((.*?)\.]";
                $pattern2 = "[\ \,\.]";
                //echo "Teste Replace|".preg_replace($pattern,"<br>,","Espanhol (médio) requerido, inglês (médio) preferido.")."|Teste Replace";
                //echo $pattern;
                if(count($result_f) > 0){
                    foreach ($result_f as $key => $value){
                        echo "
                        <tr>
                        <td style=\"white-space:nowrap;\">".$value->call_id."
                        </td>
                        <td style=\"white-space:nowrap;\">".term($value->call_type).
                        "</td>
                        <td>
                            <a id=\"ctl00_cphBody_SearchResults1_ctl01_gvList_ctl02_Hyperlink1\" href=\"http://45.55.203.7/es/calls/details/".$value->sr_number."\">".$value->pos_title."</a>
                            <br /><i>".$value->org_name."</i>
			</td>
                        <td>
                        ".$value->country."
			</td>
                        <td>
                            <nobr>
                            <span style=\"font-style:normal;\">".preg_replace($pattern2,",",preg_replace($pattern,",",$value->languages))."</span>		
                            </nobr>
			</td>
                        <td style=\"white-space:nowrap;\">
				&nbsp;".$value->beg_date."
				<br>
				&nbsp;".$value->end_date."
			</td>
                    </tr>"; 
                    }
                }
                

                ?>
		</tbody>
            <tfoot>

		</tfoot>
	</table>
</div>

    
<script>
</script>





</div>
</form>
<div id="ctl00_pnlFooter">
	

    
	<div class="clear"></div> 
    	
    	
        <br><br><br><br></br></br></br></br>
        
  
</div>
  <div class="centerNav" id="footerNav">
      	




</div>

</div>

</body>


<!-- Mirrored from www.adventistvolunteers.org/LongTerm/SearchResults.aspx?NewListing=1&Title=New%20Listings by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 13 Nov 2017 12:03:40 GMT -->
</html>

